server:
  port: 7002

eureka:
  instance:
    prefer-ip-address: false
    hostname: eureka7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/